include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  
  errors:
    invalid_annotation_target: ignore

linter:
  rules:

    # Public member uchun documentation talab qilmaslik (ixtiyoriy)
    public_member_api_docs: false
    
    # File names (ixtiyoriy)
    file_names: true