name: uv_pos
description: "pos system"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.5.1
  firebase_app_check: ^0.3.2+4
  firebase_storage: ^12.4.4
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  cloud_firestore: ^5.6.5
  flow_builder: ^0.1.0
  meta:
  intl:
  flutter_bloc: ^9.1.0
  otp_text_field_v2: ^1.0.3
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  rflutter_alert: ^2.0.7
  flutter_typeahead: ^5.2.0
  searchbar_animation: ^0.0.4
  just_audio: ^0.9.46
  pdf: ^3.11.3
  path_provider: ^2.1.5
  grouped_list: ^6.0.0
  platform: ^3.1.6
  file: ^7.0.1
  open_filex: ^4.7.0
  # open file
  image_picker: ^1.1.2
  image:
  image_cropper: ^9.0.0
  animated_search_bar: ^2.8.0
  #restartApp
  restart_app: ^1.4.0-beta
  social_auth_buttons: ^2.0.2
  flutter_slidable: ^4.0.0
  share_plus: ^10.1.4

  #wave animation loading
  flutter_spinkit: ^5.2.1

  excel: ^4.0.6
  barcode: ^2.2.9
  flutter_svg: ^2.0.17
  # syncfusion
  syncfusion_flutter_charts: ^28.2.11
  syncfusion_flutter_barcodes: ^28.2.11
  syncfusion_flutter_xlsio: ^28.2.11
  #Toast
  fluttertoast: ^8.2.12
  multi_selection_filter: ^0.0.6

  # #splash
  # animated_splash_screen: ^1.2.0

  # Qr Code
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^6.0.7
  # for printer
  esc_pos_utils_plus: ^2.0.4

  #google
  google_sign_in: ^6.3.0
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  month_picker_dialog:



dev_dependencies:
  bloc_test:
  freezed:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  analyzer:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/doc/

