// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQpWJQW0MrSLw4hItXp3yGbU0QbTRca0w',
    appId: '1:170801108120:web:7739860b5bbbc804c2aced',
    messagingSenderId: '170801108120',
    projectId: 'uv-pos',
    authDomain: 'uv-pos.firebaseapp.com',
    storageBucket: 'uv-pos.appspot.com',
    measurementId: 'G-L7KP21KF82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__Dt8t3Z_PukrTg2r7X39xfy-QRxy6mE',
    appId: '1:170801108120:android:97db596d69365ec2c2aced',
    messagingSenderId: '170801108120',
    projectId: 'uv-pos',
    storageBucket: 'uv-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfQrL3X5UJ-E_sMJragSjvIas3lynGmk',
    appId: '1:170801108120:ios:a0537794e83d6ee5c2aced',
    messagingSenderId: '170801108120',
    projectId: 'uv-pos',
    storageBucket: 'uv-pos.appspot.com',
    iosBundleId: 'inc.futuretechnologies.presidentftinc.freelance.flutter.uvPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfQrL3X5UJ-E_sMJragSjvIas3lynGmk',
    appId: '1:170801108120:ios:a0537794e83d6ee5c2aced',
    messagingSenderId: '170801108120',
    projectId: 'uv-pos',
    storageBucket: 'uv-pos.appspot.com',
    iosBundleId: 'inc.futuretechnologies.presidentftinc.freelance.flutter.uvPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQpWJQW0MrSLw4hItXp3yGbU0QbTRca0w',
    appId: '1:170801108120:web:b1796e7c52526486c2aced',
    messagingSenderId: '170801108120',
    projectId: 'uv-pos',
    authDomain: 'uv-pos.firebaseapp.com',
    storageBucket: 'uv-pos.appspot.com',
    measurementId: 'G-4JZNG2S4D6',
  );
}
